### PR TITLE
Optimize cache to lock per key

### PR DESCRIPTION
**Pull request by jjxtra**

### CODE REVIEW

**Comment by alastairtree** [comment]
Thank you. Can you give any guidance on how you arrived at the 8192 lock count?

**Comment by jjxtra** [comment]
8192 is somewhat arbitrary. The lower this number, the more likely the key hash will collide. The higher the number, the more ram used. 32K seemed like a nice balance of likely few to no collisions and low RAM usage.

**Comment by alastairtree** [comment]
The worst case scenario during lock acquisition is that every single thread has a unique key, and so ideally none should block each other. As the work being locked is just synchronous access to a concurrent dictionary it suggests the optimum number of keys is related to the number of cores - under max load every CPU holds one lock with a unique key. That would suggest the optimum number of locks would be similar to the number of cores/CPUs on the machine.

To test this I did some CPU bound load testing to see how many cache entries could be fetched/inserted in a fixed time window. It revealed your code is around 20 times faster than the original single lock implementation (which was similar in speed to a single keyLock version of this PR `int[] keyLocks = new int[1];`)
It also revealed that performance stops improving as you increase the number of keyLocks much beyond the number of cores on the machine:

```
# Locks  Cache req in 10s
1            6240625
2            10452129
6            19198527 
12          27735172 (test machine had 6 cores, 12 with HyperThreading)
24          27086363
32          32524781
128        32039528
1024      31144725
8000      33000461
```

As a result I will use 32 keyLocks for now, and accept this PR. 

Thank you very much.

**Comment by jjxtra** [comment]
How many concurrent requests did your performance test run? Did you use a random key per request?

**Comment by alastairtree** [comment]
I tested with a few different configs of number of async and sync threads, and the number of different cache keys and expiration times and got similar results. The test I used can be seen at https://github.com/alastairtree/LazyCache/blob/master/LazyCache.UnitTests/CachingServiceMemoryCacheProviderTests.cs#L915 but I tried it with a few different variables. Let me know if you have different results.

**Comment by jjxtra** [comment]
Something like benchmark.net would be more appropriate, see this thread: https://gist.github.com/jjxtra/f6116180b2ef5c1550e60567af506c2a#gistcomment-3154235.

I found 1024 (a tiny 4K of RAM) to be a sweet spot in that benchmark, but something like Environment.ProcessorCount * 8 would likely be adequate.

The number of concurrent requests makes the biggest difference. If you have hundreds per second, a larger value for the key locks length is better.

**Comment by alastairtree** [comment]
Yeah benchmark dot net is great, and would be much more accurate than what I did which was certainly a quick and dirty bit of analysis!

Thanks for the link, interesting reading! 

Agree, processor count multiplier for the win, that way bigger servers that might need extra locks get them and can probably afford the additional allocations upfront, and smaller ones stay lean. My use cases do tend to be on smaller micro services hence the bias that way.

I'll be impressed if LazyCache runs on many 64 core machines, suspect most use cases are probably a bit smaller!

**Comment by jjxtra** [comment]
For anything in the cloud it will be tiny. But I use OVH for some of my servers and usually try to get a 16 or 32 core box because the cost savings are massive.

Thanks for making LazyCache, have a great week!

**Comment by alastairtree** [comment]
2.1.2 has processor count change.

**Pull request merged**
