### PR TITLE
Add TryGetValue

### PR DESCRIPTION
**Pull request by talmroth**
I actually need a Contains but since this version of MemoryCache does not have a Contains TryGetValue is the next best thing.

### CODE REVIEW

**Comment by alastairtree** [comment]
To do a contains, why not just do `Get(key) != null`? (Or GerAsync).

**Comment by talmroth** [comment]
That won’t work with value types and unfortunately I have a use case where nulls are being cached so I need a definitive way to know if a value is cached.

**Comment by dseipp** [comment]
Can this be switched to `out T` instead of `out object` if that's what is being returned here?

**Comment by alastairtree** [comment]
> Can this be switched to `out T` instead of `out object` if that's what is being returned here?

Yes that would be better! Send a PR?

**Pull request merged**
